const RN_WEBVIEW_COMMON_MESSAGE_TYPE = {
  PERMISSION_REQUEST: 'PERMISSION_REQUEST',
  PERMISSION_CHECK: 'PERMISSION_CHECK',
  SIGNIN_GOOGLE: 'SIGNIN_GOOGLE',
  SIGNIN_GOOGLE_COMPLETE: 'SIGNIN_GOOGLE_COMPLETE',
  SIGNOUT_GOOGLE: 'SIGNOUT_GOOGLE',
  SIGNIN_APPLE: 'SIGNIN_APPLE',
  SIGNIN_APPLE_COMPLETE: 'SIGNIN_APPLE_COMPLETE',
  // SIGNOUT_FACEBOOK: 'SIGNOUT_FACEBOOK',
  // SIGNIN_FACEBOOK: 'SIGNIN_FACEBOOK',
  WEB_LOAD: 'WEB_LOAD',
  EXIT_APP: 'EXIT_APP',
  APP_IS_UPDATE: 'APP_IS_UPDATE'
};

export const RN_MESSAGE_TYPE = {
  ...RN_WEBVIEW_COMMON_MESSAGE_TYPE,
  COPY: 'COPY',
  IMAGE_PICKER: 'IMAGE_PICKER'
};

export const WEBVIEW_MESSAGE_TYPE = {
  ...RN_WEBVIEW_COMMON_MESSAGE_TYPE,
  USER_LOCATION: 'USER_LOCATION',
  UUID: 'UUID',
  FCM_TOKEN: 'FCM_TOKEN',
  IMAGE_PICKED: 'IMAGE_PICKED',
  BACKBUTTON_CLICK: 'BACKBUTTON_CLICK',
  HARDWARE_BACK_BUTTON_PRESS: 'HARDWARE_BACK_BUTTON_PRESS',
  NOTIFICATION_MESSAGE_BACKGROUND: 'NOTIFICATION_MESSAGE_BACKGROUND',
  NOTIFICATION_MESSAGE: 'NOTIFICATION_MESSAGE',
  SIGNOUT_GOOGLE_COMPLETE: 'SIGNOUT_GOOGLE_COMPLETE',
  SIGNIN_GOOGLE_ERROR: 'SIGNIN_GOOGLE_ERROR',
  SIGNIN_APPLE_ERROR: 'SIGNIN_APPLE_ERROR',
  ANDROID_GPS_SETTINGS: 'ANDROID_GPS_SETTINGS',
  ANDROID_MAIN_PAGE_GPS_SETTINGS: 'ANDROID_MAIN_PAGE_GPS_SETTINGS',
  MAIN_PAGE_ACCESS: 'MAIN_PAGE_ACCESS',
  COPY_URL: 'COPY_URL',
  APP_VERSION_UPDATE: 'APP_VERSION_UPDATE'
  // SIGNOUT_FACEBOOK_COMPLETE: 'SIGNOUT_FACEBOOK_COMPLETE',
  // SIGNIN_FACEBOOK_COMPLETE: 'SIGNIN_FACEBOOK_COMPLETE',
  // SIGNIN_FACEBOOK_ERROR: 'SIGNIN_FACEBOOK_ERROR'
};
